### ISSUE TITLE
DNN 9.2 profile update does not work if Profile Property "Photo" is missing

### ISSUE THREAD

**Issue by tpluscode** [dnnsoftware/Dnn.Platform#2111]
## Description 

When creating/registering a user

```
[DNN-PC114][D:2][T:5][ERROR] Dnn.PersonaBar.Users.Services.UsersController - System.ArgumentException: Unknown UserCreateStatus value encountered
Parameter name: userRegistrationStatus
at DotNetNuke.Entities.Users.UserController.GetUserCreateStatus(UserCreateStatus userRegistrationStatus)
at Dnn.PersonaBar.Users.Components.RegisterController.Register(RegisterationDetails registerationDetails)
at Dnn.PersonaBar.Users.Services.UsersController.CreateUser(CreateUserContract contract)
```

When updating a user

```
2018-04-16 09:55:31,491 [JWIDPC159][Thread:21][FATAL] DotNetNuke.Web.Common.Internal.DotNetNukeHttpApplication - System.NullReferenceException: Object reference not set to an instance of an object. 
at DotNetNuke.Services.GeneratedImage.ProfileEventHandler.ProfileUpdated(Object sender, ProfileEventArgs profileArgs) 
at DotNetNuke.Entities.EventManager.OnProfileUpdated(ProfileEventArgs args) 
at DotNetNuke.Entities.Profile.ProfileController.UpdateUserProfile(UserInfo user)
```

## Steps to reproduce

1. Remove the photo profile property in Site Settings > Site Behaviour > User Profiles. 
2. Try registering a user or adding a new user through the Persona Bar UI. 
3. You cannot even update profiles of users.

## Current result

User is not created and is thrown an error. 
When profile is updated, an error is thrown.

## Expected result

User should be created.

## Affected version

* [x] 9.2

**Comment by tpluscode** [comment]
Fixed by #2042. 

Please see if you're happy with this issue @dnnsoftware/tag
