### ISSUE TITLE
 Can not edit page after upgrade from Dnn 9.1.0 to 9.2.0

### ISSUE THREAD

**Issue by gsedubun** [dnnsoftware/Dnn.Platform#2127]
## Description 
After upgrading to Dnn 9.2.0 i can not edit a page, the error log shows Missing WebActivatorEx.

>2018-06-22 09:44:52.458+07:00 [SCCA_N010][D:14][T:24][ERROR] DotNetNuke.Services.Exceptions.Exceptions - ~/Default.aspx?tabid=33&error=terminate
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'DotNetNuke.ExtensionPoints.ExtensionPointManager' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'WebActivatorEx, Version=2.0.0.0, Culture=neutral, PublicKeyToken=7b26dc2a43f6a0d4' or one of its dependencies. The system cannot find the file specified.
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at Microsoft.Internal.AttributeServices.GetAttributes[T](ICustomAttributeProvider attributeProvider)
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.get_InnerCatalog()
   at System.ComponentModel.Composition.Hosting.AssemblyCatalog.GetEnumerator()
   at System.Collections.Generic.List\`1..ctor(IEnumerable\`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable\`1 source)
   at DotNetNuke.ExtensionPoints.SafeDirectoryCatalog..ctor(String directory)
   at DotNetNuke.ExtensionPoints.ExtensionPointManager.InitializeMefCompositionContainer()
   at DotNetNuke.ExtensionPoints.ExtensionPointManager..cctor()
   --- End of inner exception stack trace ---
   at DotNetNuke.ExtensionPoints.ExtensionPointManager.ComposeParts(Object[] attributeParts)
   at DotNetNuke.Web.Components.Controllers.ControlBarController..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at DotNetNuke.Framework.ServiceLocator\`2.InitInstance()
   at System.Lazy\`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy\`1.get_Value()
   at Dnn.EditBar.UI.Items.AddModuleMenu.Visible()
   at System.Linq.Enumerable.WhereListIterator\`1.MoveNext()
   at System.Linq.Buffer\`1..ctor(IEnumerable\`1 source)
   at System.Linq.OrderedEnumerable\`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List\`1..ctor(IEnumerable\`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable\`1 source)
   at Dnn.EditBar.UI.Controllers.EditBarController.GetMenuItems()
   at Dnn.EditBar.UI.Controllers.ContentEditorManager.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at Dnn.EditBar.UI.HttpModules.EditBarModule.OnSkinInit(Object sender, SkinEventArgs e)
   at DotNetNuke.UI.Skins.Skin.InvokeSkinEvents(SkinEventType skinEventType)
   at DotNetNuke.UI.Skins.Skin.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at DotNetNuke.Framework.DefaultPage.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
## Steps to reproduce
by following [this](http://www.dnnsoftware.com/wiki/upgrading-dotnetnuke) tutorial on how to Upgrade Dnn 9.1.0 to 9.2.0 by copying DNN_Platform_9.2.0.366-777_Upgrade.zip into DNN folder.
## Current result
i cannot find the WebActivatorEx.dll on the Install package either, now i'm trying to build from source.
## Affected version

* [x] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by bdukes** [comment]
`WebActivatorEx` isn't something that ships with DNN.  There's probably a 3rd party extension which is referencing that.  Is that assembly in your website's `bin/` folder?  What 3rd party extensions do you have installed?

**Comment by gsedubun** [comment]
yup @bdukes  that's right, i've check the extensions and found one.

Thanks, i'll close this issue

**Comment by bdukes** [comment]
@dnnsoftware/tag does anyone know if there's a way to better handle errors during MEF catalog construction, so that an extension can't break the whole site like this?
