### ISSUE TITLE
Not able to Edit or add new  pages in Evoq 9.1.1

### ISSUE THREAD

**Issue by umerwaleed** [dnnsoftware/Dnn.Platform#2131]
## Description 
i am not able to edit or add pages after upgrading to 9.1.1 whenever i want to add the page its showing erroe "There was an error retrieving your content. Please check your internet connection."
## Current result
![error](https://user-images.githubusercontent.com/17096418/41772501-5148cc5c-7632-11e8-9a7d-6c7f530b8af3.png)
## Affected version

* [x] 9.1.1

**Comment by tpluscode** [comment]
Hello @umerwaleed. I'm sorry to see you're experiencing this issue. Please see the console output to check for any JavaScript errors. This will help us diagnose the problem

**Comment by tpluscode** [comment]
Also, please check the Manage -> Admin Logs menu following this to look for any server errors being logged.

**Comment by umerwaleed** [comment]
Thanks @tpluscode for reply I am attaching the console picture
![errorconsole](https://user-images.githubusercontent.com/17096418/41891680-e27636ac-792e-11e8-9c4a-f9d7b446c7f1.png)

**Comment by umerwaleed** [comment]
This is the error in log file   
" [Thread:7][ERROR] DotNetNuke.Framework.Reflection - DotNetNuke.Entities.Host.ServerWebRequestAdapter, ...
System.IO.FileNotFoundException: Could not load file or assembly '...' or one of its dependencies. The system cannot find the file specified.
File name: '...'
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at System.Web.Compilation.BuildManager.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase)
   at DotNetNuke.Framework.Reflection.CreateType(String TypeName, String CacheKey, Boolean UseCache, Boolean IgnoreErrors)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog]. "

**Comment by umerwaleed** [comment]
This error occur when I edit the page.

![errroredit](https://user-images.githubusercontent.com/17096418/41894070-3670902e-7937-11e8-9e7a-37956d29dec9.png)

**Comment by valadas** [comment]
This appear to be Evoq specific, I would contact evoq technical support, there are significant differences with the pages features.
