### ISSUE TITLE
Error During Search - Item has already been added.

### ISSUE THREAD

**Issue by tpluscode** [dnnsoftware/Dnn.Platform#2202]
## Description 

```
2018-08-01 07:46:40.981+00:00 [RD00155D480831][D:2][T:63][ERROR] DotNetNuke.Services.Search.Internals.LuceneControllerImpl - System.ArgumentException: Item has already been added. Key in dictionary: 'Evoq.StructuredContent.Visualizer.Components.BusinessController, Evoq.StructuredContent.Visualizer' Key being added: 'Evoq.StructuredContent.Visualizer.Components.BusinessController, Evoq.StructuredContent.Visualizer'
at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
at DotNetNuke.Services.Search.Controllers.ModuleResultController.GetModuleSearchController(ModuleInfo module)
at DotNetNuke.Services.Search.Controllers.ModuleResultController.HasViewPermission(SearchResult searchResult)
at DotNetNuke.Services.Search.Controllers.SearchControllerImpl.HasPermissionToViewDoc(Document document, SearchQuery searchQuery)
at DotNetNuke.Services.Search.Internals.SearchSecurityTrimmer.PrepareScoreDocs()
at DotNetNuke.Services.Search.Internals.LuceneControllerImpl.Search(LuceneSearchContext searchContext, Int32 retryTimes)
2018-08-01 07:46:40.997+00:00 [RD00155D480831][D:2][T:63][ERROR] DotNetNuke.Services.Search.Internals.LuceneControllerImpl - Search Index Folder Is Not Available: Item has already been added. Key in dictionary: 'Evoq.StructuredContent.Visualizer.Components.BusinessController, Evoq.StructuredContent.Visualizer' Key being added: 'Evoq.StructuredContent.Visualizer.Components.BusinessController, Evoq.StructuredContent.Visualizer', Retry 1 time(s).
```

**Comment by tpluscode** [comment]
You may want to provide more details @zyhfish

**Comment by zyhfish** [comment]
Hi @tpluscode , there is no more info about this, this is related to #2183 . thx
