### ISSUE TITLE
Personabar users/pages error retrieving 

### ISSUE THREAD

**Issue by andre6622** [dnnsoftware/Dnn.Platform#2414]
## Description of bug
In the peronabar if selecting users or pages the error shows 'There was an error retrieving your content'

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to 'personabar' logged in as superuser or admin
2. Click on 'pages'
3. Error shows

## Current result
Tested a bit and seems that on new site this is not shown because there is only one or none user present. Error shows only with multiple items. This shows also in other lists of the personabar functions as eq. site settings - 'Aliases' tab and the 'Recycle bin' tabs if multiple items are present.

## Screenshots
![image](https://user-images.githubusercontent.com/44273151/47202735-5fb77a00-d37e-11e8-89b8-9056e743c844.png)

## Error log
In Chrome inspect - Failed to load resource: the server responded with a status of 500 (Internal Server Error) - /API/PersonaBar/Pages/GetPageList?searchKey=

No error log because java?

## Affected version
* [x] 9.2.0 but was also present in earlier versions (upgraded but did not improve, that's why I report it now)

## Affected browser
Tested with Chrome and Internet Explorer

**Comment by skamphuis** [comment]
I can't reproduce this on 9.2.2 and haven't seen it on earlier version. Have you checked the Event Log for more information on the error? Since it's a 500, the error occurs on the server and should have a log, either in the logfile or in the event log.

**Comment by andre6622** [comment]
The only errors I found where in the serverlog (in the _default/logs folder) and I can't see if it is related.

2018-10-24 15:06:01,904 [xxx][Thread:25][FATAL] DotNetNuke.Framework.PageBase - An error has occurred while loading page.
System.MissingMethodException: Method not found: 'System.String DotNetNuke.Entities.Modules.PortalModuleBase.get_ModulePath()'.
   at DotNetNuke.Modules.Admin.Users.Register2.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
2018-10-24 15:06:01,904 [xxx][Thread:25][ERROR] DotNetNuke.Services.Exceptions.Exceptions - ~/Default.aspx?tabid=2232&error=An unexpected error has occurred
System.MissingMethodException: Method not found: 'System.String DotNetNuke.Entities.Modules.PortalModuleBase.get_ModulePath()'.
   at DotNetNuke.Modules.Admin.Users.Register2.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by sibabratad** [comment]
I also upgraded DNN Platform site from 8.0.4 to 9.2.1 version and getting same issues. Is there any one find solutions for this ? Getting same issue while opening Users page.
Added same issue in detail to DNN forum as well
https://www.dnnsoftware.com/answers/after-upgraded-site-to-9-21-pages-users-recyclebin-page-are-not-working

**Comment by valadas** [comment]
Ok, can you go into the DotNetNuke.log4net.config file and change the level from Error to All. Then go to your _portals\default\logs delete the file from today, do your thing and check if you get more interesting logs. After that, restore the config to Error or you will have huge log files.

I have not had this issue in 9.1.1, 9.2.2 and 9.3.0 RCs.

**Comment by valadas** [comment]
I am closing this issue due to lack of response since feb 28 and that we cannot reproduce. I would suggest doing a folder compare between your site and a clean site, maybe there is some extra dlls or something local that is causing this issue for this site.
