### ISSUE TITLE
Clean install fails with object qualifier

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#2430]
## Description of bug
When installing Dnn 9.3.0 (alpha 33 at the moment) the installer fails when using an object qualifier.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Download latest nightly build
2. During installation, enter a string for the object qualifier (in my tests I entered: oq)
3. Notice errors

## Current result
The installation fails

## Expected result
Installation should succeed if using and object qualifier

## Screenshots
If applicable, provide screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/6371568/47545755-f5419500-d8bb-11e8-9d2b-e401fa2e7266.png)

## Error log
```
0:12 Minutes   |   19% ERROR occured - System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'dbo.oq_ExportImportSettings'.
 at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
 at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
 at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
 at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
 at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
 at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
 at DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteNonQuery(String connectionString, CommandType commandType, Int32 commandTimeout, String query)
 at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec)
 ClientConnectionId:bf54ac15-dfb3-4c43-8c3f-17de8c539183
 Error Number:208,State:1,Class:16
 
 /************************************************************/
 /***** SqlDataProvider *****/
 /***** *****/
 /***** *****/
 /***** Note: To manually execute this script you must *****/
 /***** perform a search and replace operation *****/
 /***** for dbo. and oq_ *****/
 /***** *****/
 /************************************************************/
 
 /* Implement cookie consent */
 /*******************************************/
 UPDATE dbo.[oq_ExportImportSettings] 
 SET [SettingValue]=[SettingValue]+',ShowCookieConsent,CookieMoreLink'
 WHERE [SettingName] = 'PortalSettingExportList';
```

```
10/26/2018 05:03:26 [ERROR] DotNetNuke.Services.Upgrade.Upgrade System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'dbo.oq_ExportImportSettings'.
10/26/2018 05:03:26 [ERROR] DotNetNuke.Services.Upgrade.Upgrade System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'dbo.oq_ExportImportSettings'.
```

## Affected version

* [x] 9.3.0 (alpha)
* [ ] 9.2.2
* [ ] 9.2.1
* [ ] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser
Should not be browser related, but I was using Chrome

* [X] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment]
Probably introduced with #2369 , I am not sure how the sub-version sql scripts get merged and in what order, but my guess is the the script tries to modify a table that does not yet exist.

**Comment by sleupold** [comment]
@valadas 
would you mind to check, whether importexportsettings table has been create using proper OQ, thank you.
