### ISSUE TITLE
Site Import/Export fails due to pre-filled Server name on task

### ISSUE THREAD

**Issue by OllyHodgson** [dnnsoftware/Dnn.Platform#2489]
## Description of bug
On a newly installed site, the Servers box on the Site Import/Export scheduled task is pre-filled with the name of the server DNN was installed on. However, on an Azure App Service the server name frequently changes (e.g. whenever you restart the app service) which causes the scheduled task to fail. 

Therefore we should consider leaving the Servers box blank (meaning run this task on the current server) on a fresh installation.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Install DNN 9.2.2 on an Azure App Service
2. Restart the App Service, so the server name changes
3. Kick off a Site Export from PersonaBar > Settings > Site Import/Export
4. Note how the status moves to In Progress, but never completes
5. Visit PersonaBar > Settings > Scheduler
6. Edit the Site Import/Export scheduled task, removing anything from the Servers box.
7. Re-run the task
8. Re-visit PersonaBar > Settings > Site Import/Export and note the task will now run to completion

## Current result
Explain what the current result is.

## Expected result
Provide a clear and concise description of what you expected to happen.

## Screenshots
![image](https://user-images.githubusercontent.com/437224/49020708-07e40e00-f189-11e8-9946-f73e28471379.png)

## Affected version

* [x] 9.2.2

(I haven't tested older versions) 

## Affected browser

n/a

**Comment by valadas** [comment]
Can still reproduce on 9.4.0 RC

**Comment by valadas** [comment]
There was a PR regarding these servers settings that got merged, is this still an issue with 9.4.1 ?

**Comment by OllyHodgson** [comment]
@valadas I don't have a Windows box right now, so I'll need someone to do a fresh install of 9.4.1 to see. Once installed, just browse to PersonaBar > Settings > Scheduler and check the Servers box in the Import/Export task is empty.

**Comment by valadas** [comment]
For me it as always been empty, I think this only affected Azure installations and/or multi-server installations.... Anyone has a setup to test this?

**Comment by thabaum** [comment]
I cannot Export a site as I just tried and received a number of errors in error logs similar to the one below.  Site Import/Export is broken in 9.5 from what I can tell.

`AbsoluteURL:/API/SiteExportImport/ExportImport/AllJobs

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:fdb22b20-7d92-4d6e-9118-f8c8bf80d88e

ExceptionHash:Cs50MlV0qPfyRjktyxHENFTBWtc=

Message:A task was canceled.

StackTrace:

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()`

**Comment by david-poindexter** [comment]
I believe this was resolved in a later version.  @OllyHodgson we'll go ahead and close this issue, but let us know if this is still a valid issue.  Thanks!
