### ISSUE TITLE
JournalController.DeleteJournalItem can't remove deleted journals

### ISSUE THREAD

**Issue by zyhfish** [dnnsoftware/Dnn.Platform#2658]
## Description of bug
when journal item already soft deleted, and try to hard delete it, null reference exception will throw out because JournalController.DeleteJournalItem only get the undeleted items.

## Error log
2019-04-01 08:55:10.910+08:00 [DESKTOP-VE8R1FL][D:3][T:68][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetNuke.Services.Journal.JournalControllerImpl.DeleteJournalItem(Int32 portalId, Int32 currentUserId, Int32 journalId, Boolean softDelete)
   at DotNetNuke.Services.Journal.JournalControllerImpl.DeleteJournalItem(Int32 portalId, Int32 currentUserId, Int32 journalId)

## Affected version

* [x] 9.3.0
* [x] 9.2.2
* [x] 9.2.1
* [x] 9.2

**Comment by valadas** [comment]
@dnnsoftware/approvers PR is merged, please close this issue.
