### ISSUE TITLE
Exporting site stuck in "In Progress" when Visual Studio is open

### ISSUE THREAD

**Issue by 1silvertiger** [dnnsoftware/Dnn.Platform#2688]
## Description of bug
I was trying to export a site and it stayed suspended on "In Progress" indefinitely without throwing any error. The folder in `~/App_Data/ExportImport/[EXPORT_DATE]` populated with following files:

- `export.dnndb`
- `export_files.zip`
- `export_packages.zip`
- `export_templates.zip`
- `export_themes.zip`

It was missing `export_db.zip` and `export.json`. I investigated the log files and found an error saying another program was using a file it needed. Since the referenced file was in the `.vs/` folder, I figured Visual Studio was using the file. When I closed VS, the export completed properly.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Open part of a site you want to export in Visual Studio.
2. Try to export the site.

## Current result
The export begins and then gets stuck on "In Progress". If you check the folder, the files I mentioned will be there and the error will be in log.

## Expected result
DNN should show a toast or something to let me know that another program is using a file it needs or at least that it can't complete the export.

## Screenshots
None.

## Error log
```none
2019-04-10 01:57:05.985-05:00 [WEBSTU18805][D:2][T:45][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.IO.IOException: The process cannot access the file 'C:\DNN8\Portals\_default\skins\cofosp2019\.vs\CofoSP2019\v15\Server\sqlite3\db.lock' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.Compression.ZipFileExtensions.DoCreateEntryFromFile(ZipArchive destination, String sourceFileName, String entryName, Nullable`1 compressionLevel)
   at Dnn.ExportImport.Components.Common.CompressionUtil.AddFileToArchive(ZipArchive archive, String file, Int32 folderOffset, String folder)
   at Dnn.ExportImport.Components.Common.CompressionUtil.AddFileToArchive(String file, String archivePath, Int32 folderOffset, String folder)
   at Dnn.ExportImport.Components.Services.ThemesExportService.ExportData(ExportImportJob exportJob, ExportDto exportDto)
   at Dnn.ExportImport.Components.Engines.ExportImportEngine.Export(ExportImportJob exportJob, ExportImportResult result, ScheduleHistoryItem scheduleHistoryItem)
   at Dnn.ExportImport.Components.Scheduler.ExportImportScheduler.DoWork()
```

## Additional context
None.

## Affected version

* [ ] 9.3.0
* [x] 9.2.2
* [ ] 9.2.1
* [ ] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

## Affected browser

* [x] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by mitchelsellers** [comment]
Did you have the debugger attached to this site within Visual Studio at the time?

**Comment by ohine** [comment]
It wouldn’t be a bad idea to exclude the git, node and the vs folders from the export process.

**Comment by 1silvertiger** [comment]
@mitchelsellers I try the export with the debugger attached when I have access to that computer again.
@ohine How do I do that?

**Comment by valadas** [comment]
@1silvertiger this would probably have to be modified in the export code, nothing that I think is configurable.

**Comment by sureshdraut** [comment]
We are getting this exception while trying to import a site from earlier exported site template.
Our site export is getting stuck because of this.

The process cannot access the file '\\xxxxxx\xxxxxxxxx\xxxxxx\xxxxx\Portals\360\CorpReadOnly\Banners\on-site-training.jpg' 
because it is being used by another process.

DNN 9.2.2
Any idea how fix it?

**Comment by valadas** [comment]
I think this is a different issue. I suggest you check what else has that file open, maybe temporarely disabling your antivirus, maybe something else. I suggest you look at the file parameters, maybe it is readonly, or the folder permissions... Or at some tools like https://www.iobit.com/en/iobit-unlocker.php that maybe can give you some more details.
