### ISSUE TITLE
Cannot upgrade from 8.0.4 or 9.3.2 to 9.4.0 alpha

### ISSUE THREAD

**Issue by valadas** [dnnsoftware/Dnn.Platform#2823]
## Description of bug
Cannot login into the upgrade wizard when trying to upgrade from Dnn 8.0.4 to upgrade to 9.4.0 alpha

## Steps to reproduce
List the steps to reproduce the behavior:
1. Install a clean Dnn 8.0.4 instance
2. Overwrite the files with Dnn 9.4.0 upgrade zip file
3. Fire up the site
4. When the upgrade wizard comes up, try to login as host

## Current result
"Username or password not recognized" error shows up

## Expected result
Upgrade wizard should start

## Error log
In the log4net logs, I have this error:
```
2019-05-28 16:42:32,153 [DanielValadasPC][Thread:20][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.IndexOutOfRangeException: TermsTabId
   at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at System.Data.SqlClient.SqlDataReader.get_Item(String name)
   at DotNetNuke.Entities.Portals.PortalInfo.Fill(IDataReader dr)
   at DotNetNuke.Common.Utilities.CBO.FillObjectFromReader(Object objObject, IDataReader dr)
2019-05-28 16:42:44,580 [DanielValadasPC][Thread:6][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.IndexOutOfRangeException: HasAgreedToTerms
   at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at System.Data.SqlClient.SqlDataReader.get_Item(String name)
   at DotNetNuke.Security.Membership.AspNetMembershipProvider.FillUserInfo(Int32 portalId, IDataReader dr, Boolean closeDataReader)
   at DotNetNuke.Security.Membership.AspNetMembershipProvider.GetUserByUserNameFromDataStore(Int32 portalId, String username)
   at DotNetNuke.Security.Membership.AspNetMembershipProvider.<>c__DisplayClass73_0.<GetUserByUserName>b__0(CacheItemArgs _)
   at DotNetNuke.Common.Utilities.DataCache.GetCachedDataFromRuntimeCache(CacheItemArgs cacheItemArgs, CacheItemExpiredCallback cacheItemExpired)
```

## Affected version

* [x] 9.4.0 alpha
* [ ] 9.3.2
* [ ] 9.3.1
* [ ] 9.2.2
* [ ] 9.2.1
* [ ] 9.2
* [ ] 9.1.1
* [ ] 9.1
* [ ] 9.0

**Comment by ohine** [comment]
> System.IndexOutOfRangeException: HasAgreedToTerms
> System.IndexOutOfRangeException: TermsTabId

Seems to be somewhat related to the new custom terms page and gdpr items which was added in v9.3.x

cc: @donker

**Comment by valadas** [comment]
Yeah, I gonna try a 9.3.2 -> 9.4.0 just to try. My guess is that code expects the database to have those values in when using the users apis... But since the data is modified after we need to login, it fails. We probably need some defaults or something. TermsTabId is an issue but I think the failure is really with the HasAgreedToTerms part. We may need to implement some default if the data is not there to support upgrades.

**Comment by valadas** [comment]
Just tried 9.3.2 -> 9.4.0 and I am experiencing the same issue

**Comment by sleupold** [comment]
this might be a problem, as the current user is loaded before the database upgrade script has run the following statement:

ALTER TABLE {databaseOwner}{objectQualifier}UserPortals ADD
  HasAgreedToTerms BIT NOT NULL DEFAULT(0),
  HasAgreedToTermsOn DATETIME NULL,
  RequestsRemoval BIT NOT NULL DEFAULT(0)
GO

If the API does not support Null values being returned for both properties, the upgrade will fail loading the user record during the upgrade.

**Comment by donker** [comment]
This highlights an issue that runs deeper. The "new" code is running while the old DB is still in place. It is only a matter of time before something else breaks. Plus: we will always have to jump through hoops to allow this. IMHO the upgrade wizard needs to be tweaked at a later date to "free" the rest of the application to go where it wants.

**Comment by valadas** [comment]
Closing since PR got merged

**Comment by BiswaRath** [comment]
I am getting the same issue in log after upgrade from 9.2.1 to 9.3.8. How to resolve this issue in the same version 9.3.8?

 at DotNetNuke.Professional.LicenseActivation.Licensing.License.MagicKey(XmlDocument xmlDoc)
2020-10-05 09:51:15.269-04:00 [BTIW61][D:3][T:77][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.IndexOutOfRangeException: TermsTabId
   at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at System.Data.SqlClient.SqlDataReader.get_Item(String name)
   at DotNetNuke.Entities.Portals.PortalInfo.Fill(IDataReader dr)
   at DotNetNuke.Common.Utilities.CBO.FillObjectFromReader(Object objObject, IDataReader dr)
2020-10-05 09:51:16.248-04:00 [BTIW61][D:3][T:77][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.IndexOutOfRangeException: TermsTabId
   at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at System.Data.SqlClient.SqlDataReader.get_Item(String name)
   at DotNetNuke.Entities.Portals.PortalInfo.Fill(IDataReader dr)
   at DotNetNuke.Common.Utilities.CBO.FillObjectFromReader(Object objObject, IDataReader dr)
2020-10-05 09:51:16.381-04:00 [BTIW61][D:3][T:77][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetNuke.Entities.Portals.PortalInfo.get_HomeDirectoryMapPath()
   at DotNetNuke.Entities.Urls.CacheController.FindFriendlyUrlParmsConfigFilePath(Int32 portalId, Boolean& portalSpecificFound)
   at DotNetNuke.Entities.Urls.CacheController.GetParameterRedirects(FriendlyUrlSettings settings, Int32 portalId, List`1& messages)
2020-10-05 09:51:16.480-04:00 [BTIW61][D:3][T:77][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.IndexOutOfRangeException: IsSystem
   at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at System.Data.SqlClient.SqlDataReader.get_Item(String name)
   at DotNetNuke.Entities.Tabs.TabInfo.Fill(IDataReader dr)
   at DotNetNuke.Common.Utilities.CBO.FillObjectFromReader(Object objObject, IDataReader dr)
2020-10-05 09:51:16.599-04:00 [BTIW61][D:3][T:77][FATAL] DotNetNuke.Web.Common.Internal.DotNetNukeHttpApplication - System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetNuke.Entities.Portals.PortalInfo.get_HomeDirectoryMapPath()
   at DotNetNuke.Entities.Portals.PortalSettingsController.LoadPortal(PortalInfo portal, PortalSettings portalSettings)
   at DotNetNuke.Entities.Portals.PortalSettings.BuildPortalSettings(Int32 tabId, PortalInfo portal)
   at DotNetNuke.Entities.Portals.PortalSettings..ctor(Int32 tabId, PortalAliasInfo portalAliasInfo)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.Handle404OrException(FriendlyUrlSettings settings, HttpContext context, Exception ex, UrlAction result, Boolean transfer, Boolean showDebug)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.ProcessRequest(HttpContext context, Uri requestUri, Boolean useFriendlyUrls, UrlAction result, FriendlyUrlSettings settings, Boolean allowSettingsChange, Guid parentTraceId)
   at DotNetNuke.Entities.Urls.AdvancedUrlRewriter.RewriteUrl(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
2020-10-05 09:52:04.545-04:00 [BTIW61][D:3][T:77][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.IndexOutOfRangeException: IsSystem
   at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at System.Data.SqlClient.SqlDataReader.get_Item(String name)
   at DotNetNuke.Entities.Tabs.TabInfo.Fill(IDataReader dr)
   at DotNetNuke.Common.Utilities.CBO.FillObjectFromReader(Object objObject, IDataReader dr)
2020-10-05 09:52:04.554-04:00 [BTIW61][D:3][T:77][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.IndexOutOfRangeException: IsSystem
   at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at System.Data.SqlClient.SqlDataReader.get_Item(String name)
   at DotNetNuke.Entities.Tabs.TabInfo.Fill(IDataReader dr)
   at DotNetNuke.Common.Utilities.CBO.FillObjectFromReader(Object objObject, IDataReader dr)
2020-10-05 09:52:04.561-04:00 [BTIW61][D:3][T:77][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.IndexOutOfRangeException: IsSystem
   at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at System.Data.SqlClient.SqlDataReader.get_Item(String name)
   at DotNetNuke.Entities.Tabs.TabInfo.Fill(IDataReader dr)

**Comment by valadas** [comment]
@BiswaRath It looks like you are in a commercial edition, did you try contacting support ?
