### ISSUE TITLE
Form Builder Microservice: Cached Token issue when sending e-mails

### ISSUE THREAD

**Issue by berkarslan-xo** [dnnsoftware/Dnn.Platform#3261]
## Description of bug
Sending emails fails in the background after some time and it only gets fixed after cache reset or IIS reset etc.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Go to Content Forms > Create Form
2. On the Form add an e-mail field and add a name to the form.
3. Go to the configuration of the form and apply the following:
Under Notifications, enable self notifications and set it to a test e-mail
Under Form Submission, Respondent Email Notification, enable Email notifications and fill in the values.
4. Save Configurations and Form.
5. Go to edit mode on any page and add the Form to it. Publish the page.
6. Go to Manage > Users, and create a new registered user.
7. Login into the site as the newly created user, and visit the page with the form.
8. Fill in the information and submit the form.
9. Check if the e-mails arrive. If they did wait for an hour before repeating step 8

Note: It is important that the site does not restart or gets the cache cleared during the hour we are waiting so ensure there is no idle timeout which will trigger a restart.

## Current result
Email is not sent and an exception occurs.

## Expected result
Email gets sent and no exception occurs.

## Error log
[ERROR] Evoq.FormBuilder.Visualizer.Services.CanvasController - Error while calling SendResponseEmailIfConfigured for Form Response Id 9f4c45d9-e94c-4968-ba54-9d7997cefb3f and Portal 0. Exception: System.Web.HttpException (0x80004005): Unauthorized - {
  "message": "Authorization has been denied for this request."
}
   at Evoq.FormBuilder.Visualizer.Components.ApiManager.Send[T](HttpRequestMessage request, String token)
   at Evoq.FormBuilder.Visualizer.Components.ApiManager.Get[T](String requestUri, String token)
   at Polly.Policy.<>c__DisplayClass8_0`1.<Execute>b__0()
   at Polly.Retry.RetryEngine.Implementation(Action action, IEnumerable`1 shouldRetryPredicates, Func`1 policyStateFactory)
   at Polly.Policy.Execute[TResult](Func`1 action, Context context)
   at Evoq.FormBuilder.Visualizer.Components.ApiRetryManager.GetFormResponseEmailObjects(String formResponseId, Int32 portalId, Int32 userId)
   at Evoq.FormBuilder.Visualizer.Components.FormResponseEmailManager.SendResponseEmail(JObject responseObject, Int32 portalId, Int32 userId)
   at Evoq.FormBuilder.Visualizer.Services.CanvasController.<>c__DisplayClass4_0.<SubmitFormResponse>b__0(Object _)

## Affected version

* [x] 9.4.x build

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by sleupold** [comment]
@berkarslan-xo 
AFAIK, FormBuilder is an EVOQ exclusive feature, which is not part of DNN Platform.

**Comment by berkarslan-xo** [comment]
Yes, I intended to close this after I noticed that but closed another issue of mine by mistake. All sorted out now. Thanks for the notice.
