### ISSUE TITLE
404 errors are creating 503 errors

### ISSUE THREAD

**Issue by thabaum** [dnnsoftware/Dnn.Platform#3346]
## Description of bug
Provide a clear and concise description of what the bug is.

## Steps to reproduce
List the steps to reproduce the behavior:
1. Open your browser to a page that does not exist on your DNN website.
2. See Current Result

## Current result
DNN Error : No sites currently exist for this installation. - 503 Service Unavailable

## Expected result
404 error page that uses the same site skin.

## Screenshots
If applicable, provide screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/13577556/69658270-b8048500-1030-11ea-8fae-574be3cf8c1c.png)

![image](https://user-images.githubusercontent.com/13577556/69661871-09644280-1038-11ea-8e3e-00b4d3eb8f9d.png)
## Error log
A simple Page 404 Admin Log error for page is shown.

![image](https://user-images.githubusercontent.com/13577556/69661871-09644280-1038-11ea-8e3e-00b4d3eb8f9d.png)

And this error follows after:

`
Page Load Exception
  
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
Message:Session state can only be used when enableSessionState is set to true, either in a configuration file or in the Page directive. Please also make sure that System.Web.SessionStateModule or a custom session state module is included in the <configuration>\<system.web>\<httpModules> section in the application configuration.

StackTrace:

InnerMessage:Session state can only be used when enableSessionState is set to true, either in a configuration file or in the Page directive. Please also make sure that System.Web.SessionStateModule or a custom session state module is included in the <configuration>\<system.web>\<httpModules> section in the application configuration.

InnerStackTrace:

   at System.Web.UI.Page.get_Session()
   at DotNetNuke.Framework.CachePageStatePersister.Save()
   at System.Web.UI.Page.SaveAllState()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)`

## Additional context
Add any other context about the bug that may be helpful for resolution.

## Affected version

* [ ] 10.0.0 alpha build
* [x ] 9.4.2 alpha build
* [ ] 9.4.1 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer
* [ ] Edge

**Comment by valadas** [comment]
I cannot reproduce as explained. Can you add some more steps to reproduce, is the url pointing to a correct site but an inexisting page? If the url is pointing to an invalid site, then this is something different... Can you explain step by step how to get to this state please.

**Comment by leedavi** [comment]
I got this error, but I'm unsure if my error is related.  I'll make a comment to help others to trace through this problem.

I had a new install of DNN9.4.4 for development purpose.

I installed some code on the desktopmodules folder.

I used the "Create new Module" using a manifesto.

Everything works OK.

I went into edit mode to added the new module to the page.

I selected the modules and CRASH!!!  This error was the only thing on the website.

My problem was caused by me NOT updating the SQL SPROC for the modules and 1 was missing.

I installed the missing SPROC and it website started to work again.

**Comment by valadas** [comment]
@leedavi this would be different, it would not be a missing page, a 404 falsly reported as a 503...

**Comment by leedavi** [comment]
Understood, just thought it might help any investigate.

**Comment by thabaum** [comment]
This is the only issue still outstanding other than the journal link problem from a user perspective in my opinion of what I have been most focused on.  I am testing 9.5 RC this issue still exists.  Everything else so far has been working great.  The errors on my test site I have yet to see one other than this one.  To reproduce this error simply put in your yourdomain.com/badurl and this error will be on your screen unless you have a page named badurl of coarse.  That is some good food for thought as it should be using the 404 page I have created or the dnn 404 default.  But instead it is giving an installation error with a 503 service unavailable.

When connecting to a page without url redirection or page created for it you end up with an installation error instead of the 404.  Something possibly with the 404 error handler not getting the portal id?

**Comment by thabaum** [comment]
Steps to reproduce if unable:

1.  Enter in your browser yourdomain.com/badurl
2.  Assuming you do not have a page named badurl you will get this error.
![image](https://user-images.githubusercontent.com/13577556/74048682-8a6c7e00-4987-11ea-8d5c-68dc0739d482.png)

Let me know if I am only one with this issue happens on multiple server IIS versions and SQL DB versions and DNN Versions.

I can have a 404 page created or not.  I have made this error happen on all dnn instances upgraded and fresh 9.4.4 installations.

Also notice it says "DNN Error" instead of just "Error" or "Site Error" I believe this could be fixed at same time removing the DNN as it is not something I believe needs to be shown to visitors unless they need to know about the site being hosted using DNN.  On the side of security I would remove or change the DNN for any errors being posted to normal visitors.

**Comment by david-poindexter** [comment]
@valadas and @thabaum - I have been able to confirm this behavior, but only on an upgraded instance.  I'll go ahead and move this issue through triage and hopefully someone will have the time to look into this for the next release.

**Comment by mitchelsellers** [comment]
Was a 404 error page set in the IIS under WebServer?

**Comment by david-poindexter** [comment]
@mitchelsellers not in my case.

I do have some additional information to provide:  

- Setting the 404 page to "None Specified" does in fact allow IIS to render a standard 404.
- Changing the 404 page back to a simple page (only one module with `<p>404 - Not Found</p>` in the content, and setting that page to use the Xcillion 404 skin/container results in the 503 page being displayed by DNN.
- Setting the 500 page setting in Site Settings to the same page does not resolve the issue.

**Comment by thabaum** [comment]
we have a winner thank you @david-poindexter for making this clear.  This is the issue I have been having.

**Comment by thabaum** [comment]
I am going to dig deeper into this issue if I can over the next week if I have time...  I am getting testing environment and other things together to get to work here again.  Expect another "push" forward coming over the next month.

**Comment by thabaum** [comment]
I resolved this issue by changing from **memory** to **page** Host > Performance Setting.  

![image](https://user-images.githubusercontent.com/13577556/92531340-f2679900-f1e2-11ea-8387-3237cd3c1a5a.png)

Any reason "memory" would cause 404 errors to create an application error?

**Comment by mitchelsellers** [comment]
Yes, Memory Page State SHOULD NOT BE USED!

**Comment by bdukes** [comment]
Do we need to create a new issue to remove it?

**Comment by david-poindexter** [comment]
That would honestly be a great change @bdukes - to remove the option altogether.

**Comment by alibahosseini** [comment]
@thabaum thank you for your answer .
my problem was that when i enter the name of the page that doesnt exist  in my site. site shows me this message "No sites currently exist for this installation. - 503 Service Unavailable"  and i follow your answer and its was totally works for me.
