### ISSUE TITLE
An entry with the same key already exists - Possible Personabar Issue

### ISSUE THREAD

**Issue by tpperlman** [dnnsoftware/Dnn.Platform#3887]
## Description of bug
Attempting to put page in Edit mode throws "An entry with the same key already exists." error.

## Steps to reproduce
Login and click the Edit Page icon.

## Current behavior
Server returns a 500 error with a URL of https://.../Default.aspx?tabid=20&error=An+entry+with+the+same+key+already+exists.&content=0

## Expected behavior
The page should enter Edit Mode.

## Error information

```
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:47fa5cf9-f57a-4071-a96d-f10b4d05aa32
AssemblyVersion:9.6.1
PortalId:0
UserId:1
TabId:20
RawUrl:/Default.aspx?tabid=20&amp;error=An+entry+with+the+same+key+already+exists.&amp;content=0
Referrer:https://.../DesktopModules/admin/Dnn.PersonaBar/index.html?cdv=260
UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:77.0) Gecko/20100101 Firefox/77.0
ExceptionHash:Zpzc1RjJZJHwhNMyaKSP+zPV17U=
Message:An entry with the same key already exists.
StackTrace:
InnerMessage:An entry with the same key already exists.
InnerStackTrace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.SortedList`2.Add(TKey key, TValue value)
   at DotNetNuke.Entities.Modules.DesktopModuleController.GetPortalDesktopModules(Int32 portalId)
   at DotNetNuke.Web.Components.Controllers.ControlBarController.GetCategoryDesktopModules(Int32 portalId, String category, String searchTerm)
   at Dnn.EditBar.UI.Items.AddModuleMenu.Visible()
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Dnn.EditBar.UI.Controllers.EditBarController.GetMenuItems()
   at Dnn.EditBar.UI.Controllers.ContentEditorManager.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at Dnn.EditBar.UI.HttpModules.EditBarModule.OnSkinInit(Object sender, SkinEventArgs e)
   at DotNetNuke.UI.Skins.Skin.InvokeSkinEvents(SkinEventType skinEventType)
   at DotNetNuke.UI.Skins.Skin.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at DotNetNuke.Framework.DefaultPage.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
```

## Additional context
The site was recently upgraded to DNN v9.6.1, it is also running the latest version of 2SXC. The error message appears to be caused by duplicate Desktop Modules, but I do not see any duplicates in the ModuleDefinitions table.

## Affected version
* [X] 09.06.01 latest supported release

## Affected browser
Any

**Comment by sleupold** [comment]
did you check DesktopModules and PortalDesktopModules tables for duplicate entries as well?

**Comment by tpperlman** [comment]
@sleupold The site was developed a couple years back and has two modules that have the same FriendlyName in the DesktopModules table, but different FolderName and ModuleName. Same with the ModuleDefinitions table, FriendlyName the same but different DefinitionName. I changed the friendly name of each to be different and the issue persists so it must be something else.

I also looked for duplicate entries in the PortalDesktopModules table, but there are no duplicates there either.

**Comment by bdukes** [comment]
@tpperlman did you clear the cache after changing the friendly names?  I would expect that the friendly name collision is the culprit, but the old duplicate names may just still be cached.

**Comment by tpperlman** [comment]
@bdukes I cleared the cache and recycled the app, no change. We were previously running DNN v9.4 or so before we updated and haven't had this issue until we updated to v9.6.1. I can't be 100% it isn't related to 2SXC since I had an issue on another DNN install that corrupted some content types and returned the same error, but that error only appeared when I opened the window to manage a 2sxc app.

Is there a query or stored proc I can run that returns the exact data for  _DotNetNuke.Entities.Modules.DesktopModuleController.GetPortalDesktopModules(Int32 portalId)_ so that I can see if it contains any duplicate data?

**Comment by bdukes** [comment]
It's calling the `GetPortalDesktopModules` stored procedure (passing in either the portal ID or `NULL`)

**Comment by tpperlman** [comment]
Great pointers, guys. I had changed the FriendlyName for the app in the PB, but it didn't change it in the DesktopModules table, only in the ModuleDefinitions table. Once I updated the actual DesktopModules table's FriendlyName the issue went away.

I guess duplicate module FriendlyNames are a no-no, but this wasn't the case before.

Thanks for the help @sleupold and @bdukes
