### ISSUE TITLE
TokenProvider Null Reference Exception

### ISSUE THREAD

**Issue by ahoefling** [dnnsoftware/Dnn.Platform#3986]
## Description of bug
When using the latest code in the `develop` branching which currently is targeting 9.7.0 modules that leverage the **TokenProvider** are no longer working. I have a site that uses 2sxc content and when I used the latest codebase none of the modules would load. Other modules such as MVC and WebForms modules are still working.

## Steps to reproduce
1. Install latest develop code base targetting 9.7.0
2. Install a module using token providers such as 2sxc

## Current behavior
The module fails to load with a Null Reference Exception

## Expected behavior
The module should load correctly

## Screenshots
![image](https://user-images.githubusercontent.com/17751436/90322807-da279580-df26-11ea-9a2f-ef73d21c0197.png)

## Error information
```
Error: About Me is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object. at DotNetNuke.Services.Tokens.BaseCustomTokenReplace.ReplaceTokens(String sourceText) in D:\DNN\Dnn.Platform\DNN Platform\Library\Services\Tokens\BaseCustomTokenReplace.cs:line 199 at DotNetNuke.Services.Tokens.TokenReplace.ReplaceTokens(String sourceText) in D:\DNN\Dnn.Platform\DNN Platform\Library\Services\Tokens\TokenReplace.cs:line 271 at ToSic.Sxc.Dnn.LookUp.GetDnnEngine.GetEngine(Int32 instanceId, ILog parentLog) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2sxc Dnn\Dnn\LookUp\GetDnnEngine.cs:line 26 at ToSic.Sxc.LookUp.ConfigurationProvider.GetConfigProviderForModule(Int32 moduleId, IApp app, ICmsBlock cms) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\LookUp\ConfigurationProvider.cs:line 79 at ToSic.Sxc.LookUp.ConfigurationProvider.<>c__DisplayClass1_0.<Build>b__0(App appToUse) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\LookUp\ConfigurationProvider.cs:line 32 at ToSic.Eav.Apps.App.get_ConfigurationProvider() in C:\Projects\eav-server\ToSic.Eav.AppEngine\App_Data.cs:line 21 at ToSic.Sxc.Blocks.BlockFromModule.get_Data() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\Blocks\BlockFromModule.cs:line 27 at ToSic.Sxc.Engines.EngineBase.Init(ICmsBlock cmsBlock, Purpose purpose, ILog parentLog) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\Engines\EngineBase.cs:line 64 at ToSic.Sxc.Blocks.CmsBlock.GetEngine(Purpose renderingPurpose) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\Blocks\CmsBlock_Render.cs:line 133 at ToSic.Sxc.Dnn.Web.DnnClientResources.EnsurePre1025Behavior() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2sxc Dnn\Dnn\Web\DnnClientResources.cs:line 56 at ToSic.SexyContent.View.TryCatchAndLogToDnn(Action action, Action`1 timerWrap) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\View.ascx.cs:line 154 --- End of inner exception stack trace ---
```

## Additional context
I think this may effect HTML modules and legacy CSHTML/Razor Modules. It does not effect MVC or WebForms

## Affected version

* [x] 10.00.00 alpha build
* [x] 09.07.00 release candidate
* [ ] 09.06.02 latest supported release

## Affected browser
The problem is server side, this is not applicable

**Comment by valadas** [comment]
I am trying to understand, is 2sxc already using the new probider or is it the existing codebase that now breaks or is it some sort of clash with a concurent provider?

**Comment by ahoefling** [comment]
This was caused using the LTS build of 2sxc 10.25.3. I really don't know much about the inner workings of that module except they heavily leverage the tokening system in DNN. My guess is HTML (token) modules are not working. Was there an API change or something that the 2sxc api might be leveraging? This very well could be a problem with 2sxc but I wanted to start by reporting it here, because we shouldn't be breaking modules on minor releases 9.6.2->9.7.0

![image](https://user-images.githubusercontent.com/17751436/90323602-8b332d80-df31-11ea-9a75-945665d703c2.png)

**Comment by bdukes** [comment]
Does your `web.config` have the new `<tokens>` section?

**Comment by ahoefling** [comment]
I did not, I'll try running a full update to the release client and see what happens.

**Comment by ahoefling** [comment]
I just completed an upgrade from 9.6.2 -> 9.7.0-rc2 and the original error has gone away. 🎉 great news 🎉

There is a new problem and I am not 100% sure if it is a breaking change, but the **Stream** feature of 2sxc is no longer working on the latest LTS build 10.25.2. The only thing in the stack trace that is not 2sxc code is references to the `System.Web.WebPages.WebPageBase`, was there any changes in the dll we reference for that or perhaps a web.config change. The modules using streams were working in 9.6.2 and now they aren't with 9.7.0-rc2.

```AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:2c8bc683-1f97-4cd9-ad9d-bd8634810b2a

AssemblyVersion:

PortalId:-1

UserId:-1

TabId:-1

RawUrl:

Referrer:

UserAgent:

ExceptionHash:b7FgndJm0/HMtnIzVIsI6xiKLdo=

Message:Error getting List of Stream. Stream Name: Default DataSource Name: CacheAllStreams

StackTrace:

   at ToSic.Eav.DataSources.DataStream.<get_List>g__EntityListDelegate|20_0() in C:\Projects\eav-server\ToSic.Eav.DataSources\Streams\DataStream.cs:line 100
   at ToSic.Eav.DataSources.Caching.ListCache.GetOrBuild(IDataStream stream, Func`1 builderFunc, Int32 durationInSeconds) in C:\Projects\eav-server\ToSic.Eav.DataSources\Caching\ListCache.cs:line 94
   at ToSic.Eav.DataSources.DataStream.get_List() in C:\Projects\eav-server\ToSic.Eav.DataSources\Streams\DataStream.cs:line 110
   at ToSic.SexyContent.Razor.SexyContentWebPage.AsDynamic(IDataStream stream) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\SexyContentWebPage.cs:line 94
   at ASP._Page_Portals_2_2sxc_Blog_App__FeaturedBlogs_cshtml.Execute() in e:\AndrewHoefling.dnn.dev\Website\Portals\2\2sxc\Blog App\_FeaturedBlogs.cshtml:line 2
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at ToSic.Sxc.Engines.RazorEngine.Render(TextWriter writer) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\Engines\Razor\RazorEngine.cs:line 82
   at ToSic.Sxc.Engines.RazorEngine.RenderTemplate() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\Engines\Razor\RazorEngine.cs:line 92
   at ToSic.Sxc.Engines.EngineBase.Render() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\Engines\EngineBase.cs:line 108
   at ToSic.Sxc.Blocks.CmsBlock.Render() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\Blocks\CmsBlock_Render.cs:line 54
InnerMessage:Error getting List of Stream. Stream Name: Default DataSource Name: Paging

InnerStackTrace:

   at ToSic.Eav.DataSources.DataStream.<get_List>g__EntityListDelegate|20_0() in C:\Projects\eav-server\ToSic.Eav.DataSources\Streams\DataStream.cs:line 100
   at ToSic.Eav.DataSources.DataStream.get_List() in C:\Projects\eav-server\ToSic.Eav.DataSources\Streams\DataStream.cs:line 115
   at ToSic.Eav.DataSources.DataStream.<get_List>g__EntityListDelegate|20_0() in C:\Projects\eav-server\ToSic.Eav.DataSources\Streams\DataStream.cs:line 92
Source:ToSic.Eav.DataSources

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

Server Name: DESKTOP-8L05G7S


```

**Comment by ahoefling** [comment]
Can I get someone else to give this a try? Should I update the bug description or should I close this and open a new bug?
