### ISSUE TITLE
DnnImageHandler General Exception Error

### ISSUE THREAD

**Issue by msr930** [dnnsoftware/Dnn.Platform#3993]
DnnImageHandler doesn't work since I moved my website from my local server to a host. I have no Idea How to fix it. The Error occurs whenever DnnImageHandler calls a user's profile image or any other profile property of image type. No user images are shown. Note that on my local development server DnnImageHandler works fine. DnnImageHandler recurring Error:

Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.8.4075.0

DNN 9.4.1

AbsoluteURL:/DnnImageHandler.ashx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:d741bc90-73c2-4a85-af1c-d0f2e21547d4

AssemblyVersion:
 

ExceptionHash:7kgL5R6baI4X2Yh8vqcikOx2+Bs=

Message:Unhandled Error:

StackTrace:

InnerMessage:Parameter is not valid.

InnerStackTrace:

   at System.Drawing.Image.FromStream(Stream stream, Boolean useEmbeddedColorManagement, Boolean validateImageData)
   at DotNetNuke.Services.GeneratedImage.ImageHandlerInternal.GetImageThroughTransforms(Byte[] buffer)
   at DotNetNuke.Services.GeneratedImage.ImageHandlerInternal.HandleImageRequest(HttpContextBase context, Func`2 imageGenCallback, String uniqueIdStringSeed)
   at DotNetNuke.Services.GeneratedImage.ImageHandler.ProcessRequest(HttpContextBase context)
   at DotNetNuke.Services.GeneratedImage.ImageHandler.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by msr930** [comment]
I forgot to mention that my local development PC runs Windows 10 64 bit edition while the host server runs Win 32 bit edition. DnnImageHundler runs perfectly on my PC while it passes general exceptions on the host server.

**Comment by sleupold** [comment]
the component being used might not support 32 bit Windows (which is quite uncommon nowadays for servers)

**Comment by msr930** [comment]
I rechecked and I was wrong the server runs Win 64 bit

**Comment by msr930** [comment]
Ok Problem solved. I contacted the server administrator. Apparently "Enable 32-bit applications" was enabled in the IIS configuration. Disabling it solved the issue. I appreciate your help Sebastian.

**Comment by sleupold** [comment]
@msr930 
Thank you for re-checking it :)
