### ISSUE TITLE
Deleting connection Analytics removes all connectors

### ISSUE THREAD

**Issue by Tychodewaard** [dnnsoftware/Dnn.Platform#4111]
## Description of bug
If you have a Google Analytics connection set up and you want to remove that connection, that is not possible.
1. You can not just remove the ua-code and hit save
2. if you choose 'delete connection', you destroy the Connectors part. The connections setting just says "Setup your connections to easily share content and more". So there is no Analytics and no Azure connectors anymore

## Steps to reproduce
Go to COnnectors, save a ua-code, remove the ua-code (does not work) and click 'delete connection'.

## Expected behavior
1. If I empty the ua-code field, I would like to be able to save that. Or have a 'reset-button;. But it must be possible to remove a ua-code.
2. whatever the 'delete connection' button is supposed to do, probably not this.

## Error information
Message:Object reference not set to an instance of an object.

StackTrace:

   at DNN.Connectors.GoogleAnalytics.GoogleAnalyticsConnector.GetConfig(Int32 portalId)
   at DNN.Connectors.GoogleAnalytics.GoogleAnalyticsConnector.HasConfig(Int32 portalId)
   at Dnn.PersonaBar.Connectors.Services.ConnectorsController.<GetConnections>b__1_0(IConnector x)
   at DotNetNuke.Collections.CollectionExtensions.ForEach[TType](IEnumerable`1 source, Action`1 action)
   at Dnn.PersonaBar.Connectors.Services.ConnectorsController.GetConnections()
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
InnerMessage:

InnerStackTrace:

Source:DNN.Connectors.GoogleAnalytics

## Affected version
9.6.1 but as this part has not changed much, I think newer versions as well.

**Comment by skamphuis** [comment]
This issue is solved in #4457 as @Tychodewaard pointed out to me.
