### ISSUE TITLE
File Browser of CKEditor Error

### ISSUE THREAD

**Issue by huyenbv** [dnnsoftware/Dnn.Platform#4340]
##File manager Error
When create a secure folder and setting CKEditor to upload asset to the secure folder, exception here :
InnerStackTrace:

   at DNNConnect.CKEditorProvider.Utilities.SettingsUtil.LoadEditorSettingsByKey(PortalSettings portalSettings, EditorProviderSettings currentSettings, List`1 editorHostSettings, String key, IList`1 portalRoles)
   at DNNConnect.CKEditorProvider.Web.EditorControl.LoadAllSettings()
   at DNNConnect.CKEditorProvider.Web.EditorControl.CKEditorInit(Object sender, EventArgs e)
   at System.Web.UI.Control.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at DotNetNuke.UI.UserControls.TextEditor.OnLoad(EventArgs e)

## Description of bug
Provide a clear and concise description of the bug.

## Steps to reproduce
List the precise steps to reproduce the bug:
3. Scroll to '....'

## Current behavior
Explain the current behavior.

## Expected behavior
Provide a clear and concise description of the expected behavior.

## Screenshots
If applicable, provide screenshots to help explain the bug.

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version

* [ ] 10.00.00 alpha build
* [ ] 09.08.00 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by sleupold** [comment]
- At which DNN version did you experience this issue?
- The title is misleading, it should be "File Browser of CKEditor", not "File Manager" (deprecated admin module).
- Besides, the title should indicate the issue, e.g. "Upload to secure folder error".

**Comment by valadas** [comment]
@sleupold I updated the title

@huyenbv In addition to @sleupold comments, it's really useful to get very precise steps to reproduce in order to even start debugging and ultimatelly doing a fix.

**Comment by sleupold** [comment]
@valadas 
Thank you!
