### ISSUE TITLE
MVC module in 404 page causes system to crash on startup

### ISSUE THREAD

**Issue by miguelvaz78** [dnnsoftware/Dnn.Platform#4363]
## Description of bug
If you add an MVC module in the 404 page it will not work and will cause all mvc modules to not load if the first hit to the site is to a non existing page.

## Affected versions
* [ ] 10.00.00 alpha build
* [x] 09.08.00 latest supported release

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Edit the 404 page
2. Add a MVC module to the 404 page - I used the Contact list MVC example.
3. Navigate to a non existing page. ex: http://dnndev.me/this-page-does-not-exists
4. The module shows an unable to load error message.

## Error information
On step 4 shown above, it is recorded in the log one exception:
Module Load Exception
Message:An error occurred when trying to create a controller of type 'Dnn.ContactList.Mvc.Controllers.ContactController'. Make sure that the controller has a parameterless public constructor.
StackTrace:
InnerMessage:
An error occurred when trying to create a controller of type 'Dnn.ContactList.Mvc.Controllers.ContactController'. Make sure that the controller has a parameterless public constructor.
InnerStackTrace:
```
   at System.Web.Mvc.DefaultControllerFactory.DefaultControllerActivator.Create(RequestContext requestContext, Type controllerType)
   at System.Web.Mvc.DefaultControllerFactory.CreateController(RequestContext requestContext, String controllerName)
   at DotNetNuke.Web.Mvc.Framework.Modules.ModuleApplication.ExecuteRequest(ModuleRequestContext context)
   at DotNetNuke.Web.Mvc.MvcHostControl.ExecuteModule()
```

If you restart the server and the first requests hits the not found page (example above) the MVC system breaks and all mvc modules in any page stop working.
In this case, the system registers the following error when loading the MVC modules. It seams that the startup breaks and some context is not successfully created, that breaks the MVC system.
This is resolved by manually restarting the server and hitting a page that exists.

Message:IServiceScope not provided
StackTrace:
InnerMessage:IServiceScope not provided
InnerStackTrace:
```
   at DotNetNuke.Web.Mvc.DnnMvcDependencyResolver.GetService(Type serviceType)
   at System.Web.Mvc.DependencyResolverExtensions.GetService[TService](IDependencyResolver resolver)
   at System.Web.Mvc.SingleServiceResolver`1.GetValueFromResolver()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at System.Web.Mvc.SingleServiceResolver`1.get_Current()
   at System.Web.Mvc.DefaultControllerFactory.get_ControllerActivator()
   at System.Web.Mvc.DefaultControllerFactory.GetControllerInstance(RequestContext requestContext, Type controllerType)
   at System.Web.Mvc.DefaultControllerFactory.CreateController(RequestContext requestContext, String controllerName)
   at DotNetNuke.Web.Mvc.Framework.Modules.ModuleApplication.ExecuteRequest(ModuleRequestContext context)
   at DotNetNuke.Web.Mvc.MvcHostControl.ExecuteModule()
```

Help is appreciated. Thanks!!

**Comment by jacoch** [comment]
Glad to find that bug report. Was searching for several days what could cause one of our web site to crash sometime. I was sure it has something to do with 404 page, as the web site was replacing an older one and thus having a lot of 404 due to existing links. But did not find the link to MVC module. Will change the page in the meantime to avoid these crashes. Thanks.

**Comment by jacoch** [comment]
Did someone check a newer version? Is this bug still unresolved? It's quite complicated to explain customers that the mvc modules we wrote can't be used in the 404 error page.
