### ISSUE TITLE
HTTP error occurred during file upload (error status: 500)

### ISSUE THREAD

**Issue by brewadmin** [dnnsoftware/Dnn.Platform#4555]
## Description of bug
When trying to upload an image in the CK text editor. I select the image within File Manager on PC and then attempt to send to server. This returns the error HTTP error occurred during file upload (error status: 500)

## Steps to reproduce
List the precise steps to reproduce the bug:
3. Scroll to '....'

## Current behavior
Explain the current behavior.

## Expected behavior
Provide a clear and concise description of the expected behavior.

## Screenshots
If applicable, provide screenshots to help explain the bug.
![image](https://user-images.githubusercontent.com/13762791/110487218-06d71080-80f6-11eb-8df7-203cbc097126.png)

## Error information
Provide any error information (console errors, error logs, etc.) related to this bug.

## Additional context
Provide any additional context that may be helpful in understanding and/or resolving the bug.

## Affected version

* [ ] 10.00.00 alpha build
* [ ] 09.09.00 latest supported release

## Affected browser

* [ ] Chrome
* [ ] Firefox
* [ ] Safari
* [ ] Internet Explorer 11
* [ ] Microsoft Edge (Classic)
* [ ] Microsoft Edge Chromium

**Comment by brewadmin** [comment]
Will check

 

 

Kind regards

 

Brent Wilson

ITM Website Design, SEO and Digital Marketing

084 7515 616

 <http://www.itm.co.za/> www.itm.co.za

**Comment by brewadmin** [comment]
2021-03-09 16:52:47,262 [triindex][Thread:70][FATAL] DotNetNuke.Web.Common.Internal.DotNetNukeHttpApplication - System.Web.HttpUnhandledException (0x80004005): Exception of type 'System.Web.HttpUnhandledException' was thrown. ---> System.ArgumentNullException: Value cannot be null.

Parameter name: input

   at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)

   at System.Text.RegularExpressions.Regex.Replace(String input, String pattern, String replacement, RegexOptions options)

   at DNNConnect.CKEditorProvider.Browser.Browser.GetJsUploadCode(String fileName, String fileUrl)

   at DNNConnect.CKEditorProvider.Browser.Browser.UploadFile(HttpPostedFile file, String command)

   at DNNConnect.CKEditorProvider.Browser.Browser.Page_Load(Object sender, EventArgs e)

   at System.Web.UI.Control.OnLoad(EventArgs e)

   at System.Web.UI.Control.LoadRecursive()

   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

   at System.Web.UI.Page.HandleError(Exception e)

   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

   at System.Web.UI.Page.ProcessRequest(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

   at System.Web.UI.Page.ProcessRequest()

   at System.Web.UI.Page.ProcessRequest(HttpContext context)

   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()

   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)

   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

 

Kind regards

 

Brent Wilson

ITM Website Design, SEO and Digital Marketing

084 7515 616

 <http://www.itm.co.za/> www.itm.co.za

**Comment by brewadmin** [comment]
Hi David

 

I upgraded from DNN 9.8.1 to DNN 9.9

 

Unfortunately, I could not have 70 websites crippled by the upgrade to 9.9 so I have rolled back to 9.8.1

 

I shall wait for the issues to be addressed before attempting upgrade again

 

Kind regards

 

Brent Wilson

ITM Website Design, SEO and Digital Marketing

084 7515 616

 <http://www.itm.co.za/> www.itm.co.za

**Comment by valadas** [comment]
Well, the issue won't be addressed if we cannot make it happen 😄 

The first step is understanding why this is happening to you and the changes I am talking about where done before 9.8.1, did you check the web.config provider you are using ?

**Comment by valadas** [comment]
Ok, so that is the correct provider, now let's check it's version, if you go to Extensions then select Providers in the dropdown, does that version match the Dnn installed version ?

![image](https://user-images.githubusercontent.com/6371568/110695216-97295a00-81b7-11eb-8fba-5a22176d102f.png)

If not, what version do you see ?

**Comment by james7342** [comment]
I can get the same error. I cannot reproduce it though using the same method. Using the file upload option as describe above doesn't result in the error. What does reproduce the error for me is. 
1. In CKEditor Drop and Drag an Image into the editor area.
2. Get Upload Success messages
3. Proceeded by 500 Error
![screenshot_2130](https://user-images.githubusercontent.com/27960723/111030154-9fe77f00-83b5-11eb-919b-a3d88fa88e2e.png)

The image though still uploads to the Portal Root folder in my case. I can reproduce my test case on 2 different 9.9.0 instances. I cannot duplicate the same though on a 9.8.1 instance. The Drop and Drag doesn't do anything. Doesn't even appear to be supported in the old editor version. 

Both 9.9.0 instances were updated from 9.8.1 that have upgraded from various version over the years.

Provider Version:
![screenshot_2133](https://user-images.githubusercontent.com/27960723/111030301-3fa50d00-83b6-11eb-9d62-7b279660ef2f.png)

CKEditor Version:
![screenshot_2134](https://user-images.githubusercontent.com/27960723/111030312-4cc1fc00-83b6-11eb-90d1-f764b90564d2.png)

Log from Portals/_default/Logs
[2021.03.13.log.txt](https://github.com/dnnsoftware/Dnn.Platform/files/6134775/2021.03.13.log.txt)

Let me know if you need me to test anything else.

**Comment by valadas** [comment]
Oh yeah, I don't think it supported drag-and-drop earlier, that is new to me.

**Comment by james7342** [comment]
Looks like support started in 4.5 according to this documentation.

https://ckeditor.com/docs/ckeditor4/latest/guide/dev_file_upload.html
