### ISSUE TITLE
Import fail on 9.10

### ISSUE THREAD

**Issue by leedavi** [dnnsoftware/Dnn.Platform#5178]
## Description of bug
When importing a website template, the import fails in 9.10.

## Steps to reproduce
1. Export site template
2. Import Site Template

Import fails

## Current behavior
In 9.9 the export and import works.

## Expected behavior
Expect to work in 9.10, like in 9.9

## Error information
No error in the log.  The scheduler stops.  The portal s created without the template.

## Additional context
we have tried 9.9 export into .10 that also fails.

## Affected version
* [?] 10.00.00 alpha build
* [X ] 09.10.02 release candidate
* [? ] 09.10.01 latest supported release

**Comment by leedavi** [comment]
at DotNetNuke.Entities.Content.Workflow.WorkflowStateManager.AddWorkflowState(WorkflowState state)
   at Dnn.ExportImport.Components.Services.WorkflowsExportService.ImportData(ExportImportJob importJob, ImportDto importDto)
   at Dnn.ExportImport.Components.Engines.ExportImportEngine.Import(ExportImportJob importJob, ExportImportResult result, ScheduleHistoryItem scheduleHistoryItem)
   at Dnn.ExportImport.Components.Scheduler.ExportImportScheduler.DoWork()

**Comment by leedavi** [comment]
This seems to be a problem with multiple languages.  If we try only en-US it works.  No other language works.

**Comment by bdukes** [comment]
Does the site you're importing into have the language(s) of the export enabled?

**Comment by leedavi** [comment]
We have tried with and without.  It seems to work when we do not have them enabled.  We are retesting that now.

**Comment by leedavi** [comment]
We had a template with 3 languages

en-US (Disactivated)
fr-FR (Activated)
en-GB (Disactivated)

We created a portal and imported, the import worked.

All 3 languages existed in the new portal.

We retested with the same template, this time it worked and we got 1 language (en-US) in the new portal.

There is something strange and we're having trouble recreating a definite path for the error.   Sometimes it fails, we recreate the steps with did and it works.

We're going to try and create a single language template (en-US), then see if that works as expected.

add a reply if we can pinpoint the problem.

**Comment by leedavi** [comment]
We have traced this problme down to the addition of a portal.   If we import on portal/0 it works OK.

If we created a new portal and import it fails with..

Message:New states cannot be added to system workflows.

StackTrace:

   at DotNetNuke.Entities.Content.Workflow.WorkflowStateManager.AddWorkflowState(WorkflowState state)
   at Dnn.ExportImport.Components.Services.WorkflowsExportService.ImportData(ExportImportJob importJob, ImportDto importDto)
   at Dnn.ExportImport.Components.Engines.ExportImportEngine.Import(ExportImportJob importJob, ExportImportResult result, ScheduleHistoryItem scheduleHistoryItem)
   at Dnn.ExportImport.Components.Scheduler.ExportImportScheduler.DoWork()


In the import config the WORKFLOW is set to 102... the same as VOCABULARIES

			{
				"TotalItemsString": "102",
				"ProcessedItemsString": "0",
				"Category": "VOCABULARIES",
				"TotalItems": 102,
				"ProcessedItems": 0,
				"Completed": false,
				"ProgressPercentage": 0,
				"Order": 5
			},
			{
				"TotalItemsString": "102",
				"ProcessedItemsString": "0",
				"Category": "WORKFLOW",
				"TotalItems": 102,
				"ProcessedItems": 0,
				"Completed": false,
				"ProgressPercentage": 0,
				"Order": 6
			}

These import do not use any workflow.  and in the DB there is only 2 records and 3 records in the workflowstatus table.

Does anyone have an idea for a workaround ?

**Comment by leedavi** [comment]
![image_2022_09_15T11_08_28_672Z](https://user-images.githubusercontent.com/5583141/191017617-84861b6f-c39d-4b87-bc53-6959d719dc80.png)

The problem is that the WORKFLOW export and import does not work.  I believe it's getting the wring data.

Above is the change we made to the DNN platform.  We simply commented out 1 line, dealing with WORKFLOW and the import works.

This is defiantly a bug in DNN and stops the whole import and export functionality working on anything but portal 0.
