### ISSUE TITLE
9.11 RC5 upgrade: SQL error occur when using DB table prefix

### ISSUE THREAD

**Issue by allanedk** [dnnsoftware/Dnn.Platform#5293]
## Description of bug
Upgraded from 9.10 to 9.11 RC5. 
DB error occured when installer executed DB upgrade scripts: "CREATE VIEW [dbo].[vw_PortalPermissions]"

I'm quite sure this has to do with a missing table prefix in the upgrade script. The site is using a table prefix "dnn_". The script tries to SELECT from table "PortalPermission", however that table is called "dnn_PortalPermission" in this case.

## Error information
Installer wrote: 
_"Executing Script: 09.11.00.SqlDataProvider Error! (see 09.11.00.log.resources for more information)"_

Content of the log file:

`System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'dbo.PortalPermission'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteNonQuery(String connectionString, CommandType commandType, Int32 commandTimeout, String query)
   at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec)
ClientConnectionId:65b7f729-ca8a-4501-96b8-46d9e9726445
Error Number:208,State:1,Class:16

CREATE VIEW [dbo].[vw_PortalPermissions]
AS
SELECT  PP.PortalPermissionID,
        PP.PortalId,
        P.PermissionID,
        PP.RoleID,
        R.RoleName,
        PP.AllowAccess,
        PP.UserID,
        U.Username,
        U.DisplayName,
        P.PermissionCode,
        P.ModuleDefID,
        P.PermissionKey,
        P.PermissionName,
        PP.CreatedByUserID,
        PP.CreatedOnDate,
        PP.LastModifiedByUserID,
        PP.LastModifiedOnDate
FROM        dbo.[PortalPermission]    AS PP
 INNER JOIN dbo.[Permission]       AS P  ON PP.PermissionID = P.PermissionID
 LEFT  JOIN dbo.[Roles]            AS R  ON PP.RoleID       = R.RoleID
 LEFT  JOIN dbo.[Users]            AS U  ON PP.UserID       = U.UserID
`

## Affected version

* [ ] 10.00.00 alpha build
* [x] 09.11.00 release candidate
* [ ] 09.10.02 release candidate
* [ ] 09.10.01 latest supported release

**Comment by allanedk** [comment]
Update: Problem can be solved by manually executing the script with table prefix added. When the view is succesfully created, the site becomes available and seem to work fine.

**Comment by donker** [comment]
Great catch. Thanks for that test.

**Comment by donker** [comment]
Fixed

**Comment by allanedk** [comment]
Great! Thanks
