### ISSUE TITLE
After upgrading the dnn 9.11 i got the following error in the forum

### ISSUE THREAD

**Issue by rashidbilgrami** [dnnsoftware/Dnn.Platform#5482]
After upgrading to dnn 9.11 the system is throwing an error while accessing the forum page 
**### Error # 1:** 
AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:3cc49dd3-4b13-4ce2-b217-58b494f33a55

AssemblyVersion:9.11.0

PortalId:0

UserId:1

TabId:64

RawUrl:/Support.aspx

Referrer:https://www.3art.tech/Default.aspx?tabid=64&amp;error=Method+not+found%3a+%27System.Collections.Generic.Dictionary%602%3cSystem.String%2cSystem.String%3e+DotNetNuke.Entities.Host.Host.GetHostSettingsDictionary()%27.&amp;content=0

UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.76

ExceptionHash:k3XD6hSYFlTlYCN7ZJ3APeqqvRE=

Message:Method not found: 'System.Collections.Generic.Dictionary`2<System.String,System.String> DotNetNuke.Entities.Host.Host.GetHostSettingsDictionary()'.

StackTrace:

InnerMessage:Method not found: 'System.Collections.Generic.Dictionary`2<System.String,System.String> DotNetNuke.Entities.Host.Host.GetHostSettingsDictionary()'.

InnerStackTrace:

   at DotNetNuke.Modules.Forum.Configuration.get_DefaultEnableUsersOnline()
   at DotNetNuke.Modules.Forum.Configuration..ctor(Int32 ModuleID)
   at DotNetNuke.Modules.Forum.Configuration.GetForumConfig(Int32 ModuleID)
   at DotNetNuke.Modules.Forum.ForumUserInfo..ctor(Int32 ModuleId)
   at DotNetNuke.Modules.Forum.ForumUserController.UserCheck(Int32 UserID, Int32 PortalID, Int32 ModuleID)
   at DotNetNuke.Modules.Forum.ForumUserController.GetForumUser(Int32 UserID, Boolean UpdateLastVisit, Int32 ModuleID, Int32 PortalID)
   at DotNetNuke.Modules.Forum.ForumObject.get_CurrentForumUser()
   at DotNetNuke.Modules.Forum.Groups.CreateChildControls()
   at DotNetNuke.Modules.Forum.ForumBaseControl.CreateChildControls()
   at DotNetNuke.Modules.Forum.DNNForum.CreateChildControls()
   at System.Web.UI.Control.EnsureChildControls()
   at DotNetNuke.Modules.Forum.ForumBaseControl.EnsureChildControls()
   at DotNetNuke.Modules.Forum.DNNForum.Initialize()
   at DotNetNuke.Modules.Forum.ForumBaseControl.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.<LoadRecursiveAsync>d__246.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

Server Name: win5206

**### Error # 2:** 
ModuleId:550

ModuleDefId:131

FriendlyName:Forum

ModuleControlSource:DesktopModules/Forum/Forum_Container.ascx

AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:e29830d7-9cee-4173-965d-d132a296248e

AssemblyVersion:9.11.0

PortalId:0

UserId:1

TabId:64

RawUrl:/Support.aspx

Referrer:https://www.3art.tech/Default.aspx?tabid=64&amp;error=Method+not+found%3a+%27System.Collections.Generic.Dictionary%602%3cSystem.String%2cSystem.String%3e+DotNetNuke.Entities.Host.Host.GetHostSettingsDictionary()%27.&amp;content=0

UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36 Edg/108.0.1462.76

ExceptionHash:wp1AVqtplzMwXF9wuKNnQDuun7A=

Message:Method not found: 'System.Collections.Generic.Dictionary`2<System.String,System.String> DotNetNuke.Entities.Host.Host.GetHostSettingsDictionary()'.

StackTrace:

InnerMessage:Method not found: 'System.Collections.Generic.Dictionary`2<System.String,System.String> DotNetNuke.Entities.Host.Host.GetHostSettingsDictionary()'.

InnerStackTrace:

   at DotNetNuke.Modules.Forum.Configuration.get_DefaultEnableUsersOnline()
   at DotNetNuke.Modules.Forum.Configuration..ctor(Int32 ModuleID)
   at DotNetNuke.Modules.Forum.Configuration.GetForumConfig(Int32 ModuleID)
   at DotNetNuke.Modules.Forum.Container.Page_Load(Object sender, EventArgs e)
Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

Server Name: win5206

**### Error #3:** 
AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:9b02a096-2f84-40ab-ae53-af7505ab33ee

AssemblyVersion:

PortalId:-1

UserId:-1

TabId:-1

RawUrl:

Referrer:

UserAgent:

ExceptionHash:dMs6xbkTtanpVpcWd6zXFlOlUVw=

Message:Unhandled Error Adding Module to Page_heading.

StackTrace:

   at DotNetNuke.UI.Skins.Pane.InjectModule(ModuleInfo module)
   at DotNetNuke.UI.Skins.Skin.InjectModule(Pane pane, ModuleInfo module)
InnerMessage:Method not found: 'System.Collections.Generic.Dictionary`2<System.String,System.String> DotNetNuke.Entities.Host.Host.GetHostSettingsDictionary()'.

InnerStackTrace:

   at DotNetNuke.Modules.Forum.Configuration.get_DefaultEnableUsersOnline()
   at DotNetNuke.Modules.Forum.Configuration..ctor(Int32 ModuleID)
   at DotNetNuke.Modules.Forum.Configuration.GetForumConfig(Int32 ModuleID)
   at DotNetNuke.Modules.Forum.Container.Page_Init(Object sender, EventArgs e)
   at System.Web.UI.Control.OnInit(EventArgs e)
   at System.Web.UI.UserControl.OnInit(EventArgs e)
   at DotNetNuke.Entities.Modules.PortalModuleBase.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at System.Web.UI.ControlCollection.Add(Control child)
   at DotNetNuke.UI.Modules.ModuleHost.InjectModuleContent(Control content)
   at DotNetNuke.UI.Modules.ModuleHost.LoadUpdatePanel()
   at DotNetNuke.UI.Modules.ModuleHost.CreateChildControls()
   at System.Web.UI.Control.EnsureChildControls()
   at DotNetNuke.UI.Containers.Container.get_ModuleControl()
   at DotNetNuke.UI.Containers.Container.ProcessModule()
   at DotNetNuke.UI.Skins.Pane.InjectModule(ModuleInfo module)
Source:DotNetNuke

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

Server Name: win5206

**### Error #4:** 
AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:98b1e1d2-fff7-43da-92fe-558c927f30e3

AssemblyVersion:

PortalId:-1

UserId:-1

TabId:-1

RawUrl:

Referrer:

UserAgent:

ExceptionHash:3EJ+MvQB2mIdkVJ8JuTH/pls9z8=

Message:Method not found: 'System.Collections.Generic.Dictionary`2<System.String,System.String> DotNetNuke.Entities.Host.Host.GetHostSettingsDictionary()'.

StackTrace:

   at DotNetNuke.Modules.Forum.Configuration.get_DefaultEnableUsersOnline()
   at DotNetNuke.Modules.Forum.Configuration..ctor(Int32 ModuleID)
   at DotNetNuke.Modules.Forum.Configuration.GetForumConfig(Int32 ModuleID)
   at DotNetNuke.Modules.Forum.Container.Page_Init(Object sender, EventArgs e)
   at System.Web.UI.Control.OnInit(EventArgs e)
   at System.Web.UI.UserControl.OnInit(EventArgs e)
   at DotNetNuke.Entities.Modules.PortalModuleBase.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at System.Web.UI.ControlCollection.Add(Control child)
   at DotNetNuke.UI.Modules.ModuleHost.InjectModuleContent(Control content)
   at DotNetNuke.UI.Modules.ModuleHost.LoadUpdatePanel()
   at DotNetNuke.UI.Modules.ModuleHost.CreateChildControls()
   at System.Web.UI.Control.EnsureChildControls()
   at DotNetNuke.UI.Containers.Container.get_ModuleControl()
   at DotNetNuke.UI.Containers.Container.ProcessModule()
   at DotNetNuke.UI.Skins.Pane.InjectModule(ModuleInfo module)
InnerMessage:

InnerStackTrace:

Source:DotNetNuke.Modules.Forum

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

Server Name: win5206

**Comment by rashidbilgrami** [comment]
Problem resolved after upgrading forum module from the latest version
