### ISSUE TITLE
DNN 09.11.01 upgrade issue on SQL 2012

### ISSUE THREAD

**Issue by Timo-Breumelhof** [dnnsoftware/Dnn.Platform#5554]
## Description of bug
DNN 09.11.01 upgrade does not seem to run in combination with SQL 2012

## Steps to reproduce
List the precise steps to reproduce the bug:
1. Install DNN 09.10.02 on SQL 2012 (express)
2. Upgrade to 09.11.01
3. The installer halts at "66% ERROR occured - Installing PersonaBar - Dnn.PersonaBar.Extensions_09.11.01_Install.zip"

## Current behavior
The installer stops

## Expected behavior
Well.. ;-)

## Screenshots
![image](https://user-images.githubusercontent.com/8999382/221189275-11f885d2-1fd6-4bdd-9ec9-67689455951b.png)

## Error information
This is in Log4Net:

-----------------

2023-02-24 13:53:30,099 [Server][Thread:116][ERROR] DotNetNuke.Data.SqlDataProvider - System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near the keyword 'IF'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteNonQuery(String connectionString, CommandType commandType, Int32 commandTimeout, String query)
   at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec)
ClientConnectionId:e2830a7b-69e2-4e93-a370-50e2c4d5fad0
Error Number:156,State:1,Class:15

2023-02-24 13:53:30,131 [Server][Thread:116][ERROR] DotNetNuke.Data.SqlDataProvider - System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'AddIPFilter' in the database.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteNonQuery(String connectionString, CommandType commandType, Int32 commandTimeout, String query)
   at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec)
ClientConnectionId:e2830a7b-69e2-4e93-a370-50e2c4d5fad0
Error Number:2714,State:3,Class:16

2023-02-24 13:53:30,131 [Server][Thread:116][ERROR] DotNetNuke.Services.Installer.Log.Logger - SQL Execution resulted in following Exceptions: 
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near the keyword 'IF'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteNonQuery(String connectionString, CommandType commandType, Int32 commandTimeout, String query)
   at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec)
ClientConnectionId:e2830a7b-69e2-4e93-a370-50e2c4d5fad0
Error Number:156,State:1,Class:15

/**************************/
/** UpdateIPFilter SPROC **/
/**************************/

DROP PROCEDURE IF EXISTS dbo.[UpdateIPFilter]

System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'UpdateIPFilter' in the database.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteNonQuery(String connectionString, CommandType commandType, Int32 commandTimeout, String query)
   at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec)
ClientConnectionId:e2830a7b-69e2-4e93-a370-50e2c4d5fad0
Error Number:2714,State:3,Class:16

CREATE PROCEDURE dbo.[UpdateIPFilter]
	@IPFilterID		int,
	@IPAddress		nvarchar(50),
	@SubnetMask		nvarchar(50),
	@RuleType		tinyint,
	@LastModifiedByUserID int,
    @Notes          nvarchar(255)
AS 
	BEGIN
		UPDATE dbo.IPFilter 
			SET 
				IPAddress = @IPAddress,
				SubnetMask = @SubnetMask,
				RuleType = @RuleType,
				LastModifiedByUserID = @LastModifiedByUserID,
				LastModifiedOnDate = getdate(),
                Notes = @Notes
			WHERE IPFilterID = @IPFilterID
	END

System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near the keyword 'IF'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteNonQuery(String connectionString, CommandType commandType, Int32 commandTimeout, String query)
   at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec)
ClientConnectionId:e2830a7b-69e2-4e93-a370-50e2c4d5fad0
Error Number:156,State:1,Class:15

-------------

## Additional context
I think "OBJECT_TYPE [ IF EXISTS ] OBJECT_NAME" is supported from SQL 2016 and up and we support 2012 and up?
[Provide any additional context that may be helpful in understanding and/or resolving the bug.](https://sqlhints.com/tag/drop-procedure-if-exists/)

## Affected version

* [ ] 10.00.00 alpha build
* [x] 09.11.01 latest supported release

**Comment by sleupold** [comment]
There are two issues in file https://github.com/dnnsoftware/Dnn.Platform/blob/develop/Dnn.AdminExperience/Dnn.PersonaBar.Extensions/SqlDataProvider/09.11.01.SqlDataProvider

1. DNN SQL server acount might need access to information scheme - script should just check for existence of column like any other script
2.  "Create if exist" has been added to a recent version of SQL Server and should not be used in DNN.
Use IF Exists ... DROP Procedure

**Comment by bdukes** [comment]
FYI, our current [requirements](https://docs.dnncommunity.org/content/getting-started/setup/requirements/index.html#database-server) indicate we support SQL Server 2012, which still means this script needs to be updated

**Comment by Timo-Breumelhof** [comment]
> FYI, our current [requirements](https://docs.dnncommunity.org/content/getting-started/setup/requirements/index.html#database-server) indicate we support SQL Server 2012, which still means this script needs to be updated

OK, corrected my text.. :-)

**Comment by valadas** [comment]
Probably caused by https://github.com/dnnsoftware/Dnn.Platform/pull/5411

I'll try to have a look this weekend...

**Comment by jeremy-farrance** [comment]
On requirements, just a reminder (maybe for DNN v10+) that SQL Server 2012 support ended last July (2022).
[https://learn.microsoft.com/en-us/lifecycle/products/microsoft-sql-server-2012](https://learn.microsoft.com/en-us/lifecycle/products/microsoft-sql-server-2012)
 
Here is a quick summary of version lifecycles  for SQL 2012 thru 2019
[https://www.mssqltips.com/sqlservertutorial/9217/sql-server-release-dates-and-lifecycle/](https://www.mssqltips.com/sqlservertutorial/9217/sql-server-release-dates-and-lifecycle/)
 
I am NOT suggesting this shouldn't be fixed, it obviously should. But maybe DNN v10 could raise the requirements to SQL 2014 (or 2016). Or maybe this is already planned?

**Comment by mitchelsellers** [comment]
I agree we have promised support, we need to update. But we should be upping this minimum. 

(And if you have an old server it should really be updated)

**Comment by Timo-Breumelhof** [comment]
Agreed. 
BTW this was on a clients server they were "going to get rid off". They already setup a new one :-)

**Comment by dgingold** [comment]
The PlantAnApp folks say they're held up by this so won't recommend I upgrade to 9.11.1. I need to, so Resource Manager bugs get fixed.
