### ISSUE TITLE
Azure WebApp Custom Module Installation Doesn't Complete - Dnn.PersonaBar.ExtensionsErrors

### ISSUE THREAD

**Issue by tpperlman** [dnnsoftware/Dnn.Platform#5663]
## Description of bug

Not sure if anyone has come across this before on an Azure WebApp, but when we install one of our custom modules the installation never completes with the success message or creates the Host Alert with the install details. 

We provisioned an exact replica of the production server in our local environment and the installs complete as expected with the proper confirmation and host alert.

There are errors from Log4Net (provided below), and the module's Temp folder under Install isn't deleting (which is probably a result of the issue). This has continued to occur across a couple of subsequent release builds.

This poses an uncomfortable situation in that we're not able to get any confirmation that the SQL scripts have completed and that all the files have been copied successfully. The only way we can kind of guess it has been updated is by the version that appears in Extensions, reviewing some of our code updates or even manually running the SQL update scripts.

The installerlog files only includes references like these on both the Azure WebApp and our local server following an install. No further details are provided:

```
06/09/2023 02:36:02 [INFO] DotNetNuke.Services.Installer.XmlMerge Start UpdateNode: keyAttribute=name
06/09/2023 02:38:40 [INFO] DotNetNuke.Services.Installer.XmlMerge Start UpdateNode: keyAttribute=name
```

Here are some of the log entries we see, which seem to relate to the deletion of either temp data or files in the custom module's folder under DesktopModules:

```
2023-06-09 02:36:14,361 [MYSERVERID][Thread:48][ERROR] Dnn.PersonaBar.Extensions.Services.ExtensionsController - SchwabenCode.QuickIO.PathNotFoundException: The system cannot find the file specified.
   at SchwabenCode.QuickIO.Internal.InternalQuickIOCommon.NativeExceptionMapping(String path, Int32 errorCode)
   at SchwabenCode.QuickIO.Internal.InternalQuickIO.EnumerationHandleInvalidFileHandle(String path, QuickIOEnumerateOptions enumerateOptions, Int32 win32Error)
   at SchwabenCode.QuickIO.Internal.InternalQuickIO.FindPaths(String uncDirectoryPath, String pattern, SearchOption searchOption, Nullable`1 filterType, QuickIOEnumerateOptions enumerateOptions, QuickIOPathType pathFormatReturn)
   at SchwabenCode.QuickIO.Internal.InternalQuickIO.EnumerateDirectoryPaths(String path, String pattern, SearchOption searchOption, QuickIOEnumerateOptions enumerateOptions, QuickIOPathType pathFormatReturn)
   at DotNetNuke.Common.Utilities.FileSystemUtils.DeleteFolderRecursive(String strRoot)
   at DotNetNuke.Common.Utilities.FileSystemUtils.DeleteFolderRecursive(String strRoot)
   at DotNetNuke.Common.Utilities.FileSystemUtils.DeleteFolderRecursive(String strRoot)
   at DotNetNuke.Common.Utilities.FileSystemUtils.DeleteFolderRecursive(String strRoot)
   at DotNetNuke.Common.Utilities.FileSystemUtils.DeleteFolderRecursive(String strRoot)
   at DotNetNuke.Services.Installer.Installer.Install()
   at Dnn.PersonaBar.Extensions.Components.InstallController.InstallPackage(PortalSettings portalSettings, UserInfo user, String legacySkin, String filePath, Stream stream, Boolean isPortalPackage)
   at Dnn.PersonaBar.Extensions.Services.ExtensionsController.InstallPackageFile(String filePath)
   at Dnn.PersonaBar.Extensions.Services.ExtensionsController.InstallAvailablePackage(DownloadPackageDto package)
2023-06-09 02:38:50,370 [MYSERVERID][Thread:180][ERROR] Dnn.PersonaBar.Extensions.Components.InstallController - SchwabenCode.QuickIO.PathNotFoundException: The system cannot find the file specified.
   at SchwabenCode.QuickIO.Internal.InternalQuickIOCommon.NativeExceptionMapping(String path, Int32 errorCode)
   at SchwabenCode.QuickIO.Internal.InternalQuickIO.EnumerationHandleInvalidFileHandle(String path, QuickIOEnumerateOptions enumerateOptions, Int32 win32Error)
   at SchwabenCode.QuickIO.Internal.InternalQuickIO.FindPaths(String uncDirectoryPath, String pattern, SearchOption searchOption, Nullable`1 filterType, QuickIOEnumerateOptions enumerateOptions, QuickIOPathType pathFormatReturn)
   at SchwabenCode.QuickIO.Internal.InternalQuickIO.EnumerateDirectoryPaths(String path, String pattern, SearchOption searchOption, QuickIOEnumerateOptions enumerateOptions, QuickIOPathType pathFormatReturn)
   at DotNetNuke.Common.Utilities.FileSystemUtils.DeleteFolderRecursive(String strRoot)
   at DotNetNuke.Common.Utilities.FileSystemUtils.DeleteFolderRecursive(String strRoot)
   at DotNetNuke.Common.Utilities.FileSystemUtils.DeleteFolderRecursive(String strRoot)
   at DotNetNuke.Common.Utilities.FileSystemUtils.DeleteFolderRecursive(String strRoot)
   at DotNetNuke.Common.Utilities.FileSystemUtils.DeleteFolderRecursive(String strRoot)
   at Dnn.PersonaBar.Extensions.Components.InstallController.DeleteTempInstallFiles(Installer installer)
2023-06-09 02:38:50,448 [MYSERVERID][Thread:180][ERROR] Dnn.PersonaBar.Extensions.Services.ExtensionsController - SchwabenCode.QuickIO.PathNotFoundException: The system cannot find the file specified.
   at SchwabenCode.QuickIO.Internal.InternalQuickIOCommon.NativeExceptionMapping(String path, Int32 errorCode)
   at SchwabenCode.QuickIO.Internal.InternalQuickIO.EnumerationHandleInvalidFileHandle(String path, QuickIOEnumerateOptions enumerateOptions, Int32 win32Error)
   at SchwabenCode.QuickIO.Internal.InternalQuickIO.FindPaths(String uncDirectoryPath, String pattern, SearchOption searchOption, Nullable`1 filterType, QuickIOEnumerateOptions enumerateOptions, QuickIOPathType pathFormatReturn)
   at SchwabenCode.QuickIO.Internal.InternalQuickIO.EnumerateFilePaths(String path, String pattern, SearchOption searchOption, QuickIOEnumerateOptions enumerateOptions, QuickIOPathType pathFormatReturn)
   at DotNetNuke.Common.Utilities.FileSystemUtils.DeleteFolderRecursive(String strRoot)
   at DotNetNuke.Common.Utilities.FileSystemUtils.DeleteFolderRecursive(String strRoot)
   at DotNetNuke.Common.Utilities.FileSystemUtils.DeleteFolderRecursive(String strRoot)
   at DotNetNuke.Common.Utilities.FileSystemUtils.DeleteFolderRecursive(String strRoot)
   at DotNetNuke.Common.Utilities.FileSystemUtils.DeleteFolderRecursive(String strRoot)
   at DotNetNuke.Services.Installer.Installer.Install()
   at Dnn.PersonaBar.Extensions.Components.InstallController.InstallPackage(PortalSettings portalSettings, UserInfo user, String legacySkin, String filePath, Stream stream, Boolean isPortalPackage)
   at Dnn.PersonaBar.Extensions.Services.ExtensionsController.InstallPackageFile(String filePath)
   at Dnn.PersonaBar.Extensions.Services.ExtensionsController.InstallAvailablePackage(DownloadPackageDto package)
```

This is deep in DNN's internals and being an Azure production environment we're not sure how to diagnose the issue any further.

We've verified that all the files (e.g. DLLs, license, ReleaseNotes) and SQL providers in the manifest are included in the install file, so we're not sure what the "The system cannot find the file specified" is referencing.

This is a list of the folders and files that remain in the temp folder under installs, which is leading me to believe that perhaps deleting the backup files may point to the source of the issue:

- \Backup
- \bin
- \Providers
- [MyAppsName].dnn
- LICENSE.TXT
- ReleaseNotes.txt
- Resources.zip

Thank you for any pointers!

## Affected version
* [X] 09.11.00 latest supported release

**Comment by valadas** [comment]
This is kinda hard to diagnose without having that specific module and the starting situation which makes this issue not really actionable, for that reason, I'll move it to a discussion until something actionable can be establishes. When you install the module, in the DNN UI do you get any errors ?
