### ISSUE TITLE
[Bug]: Login module allows control characters

### ISSUE THREAD

**Issue by GerardSmit** [dnnsoftware/Dnn.Platform#5834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

In Discord a user reported that they received the following error:

> EXCEPTION: System.ArgumentException: '.', hexadecimal value 0x00, is an invalid character.
   at System.Xml.XmlEncodedRawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlEncodedRawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at System.Xml.XmlWriter.WriteAttributeString(String localName, String value)
   at DotNetNuke.Services.Log.EventLog.LogInfo.WriteXml(XmlWriter writer)
   at DotNetNuke.Services.Log.EventLog.LogInfo.Serialize()
   at DotNetNuke.Services.Log.EventLog.DBLoggingProvider.SendLogNotifications()
   at DotNetNuke.Services.Log.EventLog.SendLogNotifications.DoWork()

This happend because there was an attempt to log in with a username that contains an invalid character (`\0`). DNN tried to log this attempt, but the XML serializer doesn't allow null-characters causing an exception to be thrown. I don't think this is a security issue, since everything was handled fine, but maybe we should block control characters (like the null-character).

### Steps to reproduce?

I did not find a real way to reproduce this. You can however send invalid characters to the textbox with the `username` query.

1. Go to the login page (e.g. http://localhost/Login)
2. Add `?username=User%00name` to the query (e.g. http://localhost/Login?username=User%00name)

### Current Behavior

The null character will be set in the input field:

![image](https://github.com/dnnsoftware/Dnn.Platform/assets/2109929/88fdd1ed-c169-4506-847a-10c4e137c4b3)

Causing the username field to show an null character:

![image](https://github.com/dnnsoftware/Dnn.Platform/assets/2109929/2628787f-2a1e-495b-9afc-0c7d6d9e2548)

### Expected Behavior

The null character won't be shown.

### Affected Versions

9.13.0 (latest release)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GerardSmit** [comment]
It was later reported that the exception was from a custom login page. `UserController.UserLogin` was used instead of the DNN Authentication.
