### ISSUE TITLE
[Bug]: HTML Editor Manager or CKEditor

### ISSUE THREAD

**Issue by gregoriusus** [dnnsoftware/Dnn.Platform#5984]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have latest dnn version 9.13.02. When I go to HTML Editor Manager, I get error below. Also Profile page is not working. If I uninstall CK Editor, profile page is working, but then I do not have nay HTML Editor Also if I put HTML Editor Manager module on one page, same error:
RawUrl:/Host/HTMLEditorManager?portalid=undefined&amp;portpopUp=true

Referrer:xxxxx/admin/Dnn.PersonaBar/index.html?cdv=339

UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0

ExceptionHash:sRypCV4M279YBIdr0Va1bCH5Z8U=

Message:Object reference not set to an instance of an object.

StackTrace:

InnerMessage:Object reference not set to an instance of an object.

InnerStackTrace:

   at DNNConnect.CKEditorProvider.CKEditorOptions.FillInformations()
   at DNNConnect.CKEditorProvider.CKEditorOptions.Page_Load(Object sender, EventArgs e)
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at DotNetNuke.Entities.Modules.PortalModuleBase.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.<LoadRecursiveAsync>d__246.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()

### Steps to reproduce?

Go to SiteSettings, Behaviours, More, Open HTML Editor Manager.

### Affected Versions

9.13.2 (latest release)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mitchelsellers** [comment]
Have you upgraded in the past?  Did you customize the CKEditor before to add/remove/update anything?

**Comment by gregoriusus** [comment]
It's quite old site. I upgraded it recently and removed Telerik. Other things are working. 

What is in this function DNNConnect.CKEditorProvider.CKEditorOptions.FillInformations() that could return null reference?
