### ISSUE TITLE
[Bug]: JWT login fails with Unknown error "-1073741816" on ComputeHash

### ISSUE THREAD

**Issue by miguelvaz78** [dnnsoftware/Dnn.Platform#6059]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hi, recently I started having some errors using JWT login API. From time to time the system starts throwing errors on all login and extend tokens requests:
When calling /DesktopModules/JwtAuth/API/mobile/login

Message: Unknown error "-1073741816".

StackTrace:

   at System.Security.Cryptography.BCryptHashAlgorithm.HashCore(Byte[] array, Int32 ibStart, Int32 cbSize)
   at System.Security.Cryptography.HashAlgorithm.TransformBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount, Byte[] outputBuffer, Int32 outputOffset)
   at System.Security.Cryptography.SHA384Managed.HashCore(Byte[] rgb, Int32 ibStart, Int32 cbSize)
   at System.Security.Cryptography.HashAlgorithm.ComputeHash(Byte[] buffer)
   at Dnn.AuthServices.Jwt.Components.Common.Controllers.JwtController.LoginUser(HttpRequestMessage request, LoginData loginData)
   at Dnn.AuthServices.Jwt.Services.MobileController.Login(LoginData loginData) 

I think it might have something related to the problem found on this thread:
https://answers.microsoft.com/en-us/windows/forum/all/sha256-computehash-started-throwing/4e18a046-8bd6-4369-968c-93f34a1088bb

Looking at the source code it seems that concurrency is not being handled when calling the ComputeHash function here:
https://github.com/dnnsoftware/Dnn.Platform/blob/1e04695c9937d2a7e282ab00e909479501a1411b/DNN%20Platform/Dnn.AuthServices.Jwt/Components/Common/Controllers/JwtController.cs#L154

As the Hasher is static is shared across threads thus can this be the source of the problem?

If anyone can have a look at this I would gladly appreciate.

### Steps to reproduce?

I haven't been able to force the error when the system is working normally but after it errors one time any call to the login api will fail with the above error.

### Affected Versions

9.13.3 (latest release)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by miguelvaz78** [comment]
I will try and come up with a solution and submit a PR..

**Comment by box86rowh** [comment]
I grabbed and compiled this code and it fixed my issue with intermittent 401's via jwt auth, thanks!
